from __future__ import annotations
from typing import Protocol
from .domain import GovernedLLMDraft,GovernedLLMDraftLifecycleEvent,GovernedLLMDraftLifecycleStatus
from .exact_reference import PersistedGovernedLLMDraftReference
class GovernedLLMDraftQueryPort(Protocol):
    def get(self,draft_id:str)->GovernedLLMDraft|None:...
    def latest(self,stream_id:str)->GovernedLLMDraft|None:...
    def history(self,stream_id:str)->tuple[GovernedLLMDraft,...]:...
class GovernedLLMDraftRepository(GovernedLLMDraftQueryPort,Protocol):
    def append_with_lifecycle(self,value:GovernedLLMDraft,active:GovernedLLMDraftLifecycleEvent,supersession:GovernedLLMDraftLifecycleEvent|None=None)->None:...
class GovernedLLMDraftExactReferenceQueryPort(Protocol):
    def get_exact(self,reference:PersistedGovernedLLMDraftReference)->GovernedLLMDraft:...
class GovernedLLMDraftExactReferenceRepository(GovernedLLMDraftExactReferenceQueryPort,Protocol):
    def reference_for(self,draft:GovernedLLMDraft,invocation_reference)->PersistedGovernedLLMDraftReference:...
class GovernedLLMDraftLifecycleQueryPort(Protocol):
    def lifecycle_history(self,draft_id:str)->tuple[GovernedLLMDraftLifecycleEvent,...]:...
    def current_status(self,draft_id:str,version:int)->GovernedLLMDraftLifecycleStatus|None:...
    def current_active(self,stream_id:str)->GovernedLLMDraft|None:...
class GovernedLLMDraftLifecycleRepository(GovernedLLMDraftLifecycleQueryPort,Protocol):
    def append_lifecycle(self,event:GovernedLLMDraftLifecycleEvent)->None:...
