from typing import Protocol
from .domain import ClinicalAppraisalRecord
class ClinicalAppraisalRepository(Protocol):
    def append(self,value:ClinicalAppraisalRecord)->None:...
    def get(self,appraisal_id:str)->ClinicalAppraisalRecord|None:...
    def current(self,recommendation_reference:str)->ClinicalAppraisalRecord|None:...
    def history(self,recommendation_reference:str)->tuple[ClinicalAppraisalRecord,...]:...
    def by_evidence_package(self,evidence_package_id:str)->tuple[ClinicalAppraisalRecord,...]:...
class ClinicalAppraisalQueryPort(Protocol):
    def get(self,appraisal_id:str)->ClinicalAppraisalRecord:...
    def current(self,recommendation_reference:str)->ClinicalAppraisalRecord:...
    def history(self,recommendation_reference:str)->tuple[ClinicalAppraisalRecord,...]:...
    def by_evidence_package(self,evidence_package_id:str)->tuple[ClinicalAppraisalRecord,...]:...
