from __future__ import annotations
from typing import Protocol
from .domain import *
class GovernedAuditClinicalStatePort(Protocol):
    def facts(self,state_reference_id:str)->tuple[GovernedAuditClinicalFact,...]:...
class GovernedAuditEvidencePort(Protocol):
    def get(self,evidence_id:str):...
class GovernedEvidenceLifecyclePort(Protocol):
    def current_status(self,evidence)->str:...
class GovernedAuditGuidelinePort(Protocol):
    def latest(self,subject_reference:str):...
class GovernedAuditOrthopedicPort(Protocol):
    def latest(self,subject_reference:str):...
class GovernedAuditTerminologyPort(Protocol):
    def get(self,concept_id:str):...
class AuditDefenseRepository(Protocol):
    def append(self,value:DefensePackage)->None:...
    def latest(self,stream_id:str)->DefensePackage|None:...
    def history(self,stream_id:str)->tuple[DefensePackage,...]:...
    def reference_for(self,value:DefensePackage)->PersistedDefensePackageReference:...
    def reference_for_pre_link(self,value:DefensePackage)->PersistedDefensePackageReference:...
    def append_linked_reference(self,reference:PersistedDefensePackageReference,value:DefensePackage)->PersistedDefensePackageReference:...
    def get_exact(self,reference:PersistedDefensePackageReference)->DefensePackage:...
class AuditDefenseQueryPort(Protocol):
    def latest(self,stream_id:str)->DefensePackage|None:...
    def get_exact(self,reference:PersistedDefensePackageReference)->DefensePackage:...
    def reference_from_upstream(self,reference)->PersistedDefensePackageReference:...
class AuditDefenseEventPort(Protocol):
    def append(self,event:AuditDefenseEvent)->None:...
    def history(self,stream_id:str)->tuple[AuditDefenseEvent,...]:...
class MedicalDocumentTracePort(Protocol):
    def reference_exact(self,stream_id:str,version:int)->MedicalDocumentVersionReference:...
    def resolve_exact(self,reference:MedicalDocumentVersionReference):...
