from __future__ import annotations
from typing import Protocol
from .domain import *
from .exact_reference import PersistedMedicalDocumentVersionReference
class GovernedDocumentClinicalStatePort(Protocol):
    def facts(self,state_reference_id:str)->tuple[DocumentFactReference,...]:...
class GovernedDocumentTerminologyPort(Protocol):
    def get(self,concept_id:str)->DocumentTerminologyReference|None:...
class GovernedDocumentEvidencePort(Protocol):
    def get(self,evidence_id:str):...
class GovernedEvidenceLifecyclePort(Protocol):
    def current_status(self,evidence)->str:...
class CanonicalCitationQueryPort(Protocol):
    def get(self,evidence_id:str)->DocumentEvidenceReference|None:...
class GovernedGuidelineDocumentPort(Protocol):
    def latest(self,subject_reference:str):...
    def get_exact(self,reference):...
class GovernedOrthopedicDocumentPort(Protocol):
    def latest(self,subject_reference:str):...
    def get_exact(self,reference):...
class MedicalDocumentRepository(Protocol):
    def append(self,value:MedicalDocumentVersion)->None:...
    def latest(self,stream_id:str)->MedicalDocumentVersion|None:...
    def history(self,stream_id:str)->tuple[MedicalDocumentVersion,...]:...
class MedicalDocumentQueryPort(Protocol):
    def latest(self,stream_id:str)->MedicalDocumentVersion|None:...
class MedicalDocumentExactQueryPort(Protocol):
    def get_exact(self,reference:PersistedMedicalDocumentVersionReference)->MedicalDocumentVersion:...
class MedicalDocumentExactReferenceRepository(MedicalDocumentExactQueryPort,Protocol):
    def reference_for(self,value:MedicalDocumentVersion)->PersistedMedicalDocumentVersionReference:...
class DocumentTemplateRepository(Protocol):
    def get(self,document_type:DocumentType,version:str|None=None)->DocumentTemplate|None:...
class DocumentAuditPort(Protocol):
    def append(self,event:DocumentAuditEvent)->None:...
    def history(self,stream_id:str)->tuple[DocumentAuditEvent,...]:...
