"""Append-only medical documents. Revision ID: 017_medical_docs; Revises: 016_orthopedic"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="017_medical_docs";down_revision="016_orthopedic";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("medical_document_versions",sa.Column("version_id",sa.String(68),primary_key=True),sa.Column("document_stream_id",sa.String(68),nullable=False),sa.Column("version",sa.Integer,nullable=False),sa.Column("previous_version_id",sa.String(68),sa.ForeignKey("medical_document_versions.version_id",ondelete="RESTRICT")),sa.Column("document_id",sa.String(68),nullable=False),sa.Column("document_type",sa.String(48),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("review_status",sa.String(32),nullable=False),sa.Column("template_version",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("payload",postgresql.JSONB,nullable=False),sa.Column("schema_version",sa.Integer,nullable=False),sa.UniqueConstraint("document_stream_id","version",name="uq_medical_doc_stream_version"),sa.CheckConstraint("version > 0","ck_medical_doc_version_positive"))
    op.create_table("medical_document_audit",sa.Column("sequence_id",sa.BigInteger,sa.Identity(),primary_key=True),sa.Column("event_id",sa.String(68),nullable=False,unique=True),sa.Column("document_stream_id",sa.String(68),nullable=False),sa.Column("version_id",sa.String(68),nullable=False),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("actor_id",sa.String(128),nullable=False),sa.Column("decision_code",sa.String(64),nullable=False),sa.Column("reference_ids",postgresql.JSONB,nullable=False),sa.Column("policy_version",sa.String(64),nullable=False))
    for table in ("medical_document_versions","medical_document_audit"):op.execute(f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION reject_immutable_history_mutation()")
def downgrade():raise RuntimeError("medical document history cannot be destructively downgraded")
