"""Append-only LLM gateway governance. Revision ID: 019_llm_gateway; Revises: 018_audit_defense"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="019_llm_gateway";down_revision="018_audit_defense";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("llm_prompt_versions",sa.Column("prompt_version_id",sa.String(71),primary_key=True),sa.Column("template_id",sa.String(128),nullable=False),sa.Column("version",sa.Integer,nullable=False),sa.Column("previous_version_id",sa.String(71),sa.ForeignKey("llm_prompt_versions.prompt_version_id",ondelete="RESTRICT")),sa.Column("prompt_hash",sa.String(64),nullable=False),sa.Column("policy_version",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("payload",postgresql.JSONB,nullable=False),sa.Column("schema_version",sa.Integer,nullable=False),sa.UniqueConstraint("template_id","version",name="uq_llm_prompt_template_version"))
    op.create_table("llm_prompt_audit",sa.Column("sequence_id",sa.BigInteger,sa.Identity(),primary_key=True),sa.Column("event_id",sa.String(67),nullable=False,unique=True),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("request_id",sa.String(128)),sa.Column("prompt_version_id",sa.String(71),nullable=False),sa.Column("provider",sa.String(32)),sa.Column("model_id",sa.String(128)),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("policy_version",sa.String(64),nullable=False),sa.Column("payload",postgresql.JSONB,nullable=False),sa.Column("schema_version",sa.Integer,nullable=False))
    op.create_table("llm_invocations",sa.Column("sequence_id",sa.BigInteger,sa.Identity(),primary_key=True),sa.Column("invocation_id",sa.String(68),nullable=False,unique=True),sa.Column("request_id",sa.String(128),nullable=False),sa.Column("prompt_version_id",sa.String(71),nullable=False),sa.Column("provider",sa.String(32),nullable=False),sa.Column("model_id",sa.String(128),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("policy_version",sa.String(64),nullable=False),sa.Column("payload",postgresql.JSONB,nullable=False),sa.Column("schema_version",sa.Integer,nullable=False))
    for table in ("llm_prompt_versions","llm_prompt_audit","llm_invocations"):op.execute(f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION reject_immutable_history_mutation()")
def downgrade():raise RuntimeError("LLM gateway history cannot be destructively downgraded")
