from __future__ import annotations
from typing import Protocol
from .domain import ClinicalReasoningInput,ReasoningInputAuditEvent
class ClinicalReasoningInputRepository(Protocol):
    def append(self,value:ClinicalReasoningInput)->None:...
    def get(self,input_id:str)->ClinicalReasoningInput|None:...
    def latest(self,subject_reference:str)->ClinicalReasoningInput|None:...
    def history(self,subject_reference:str)->tuple[ClinicalReasoningInput,...]:...
class ClinicalReasoningInputQueryPort(Protocol):
    def get(self,input_id:str)->ClinicalReasoningInput:...
    def latest(self,subject_reference:str)->ClinicalReasoningInput:...
    def reconstruct(self,subject_reference:str,version:int)->ClinicalReasoningInput:...
class ClinicalReasoningInputAuditPort(Protocol):
    def append(self,event:ReasoningInputAuditEvent)->None:...
    def history(self,subject_reference:str)->tuple[ReasoningInputAuditEvent,...]:...
