from typing import Protocol
from .domain import *
from .exact_reference import PersistedHumanReviewReference
class LLMHumanReviewQueryPort(Protocol):
    def history(self,draft_id:str)->tuple[LLMHumanReviewEvent,...]:...
    def current_state(self,draft_id:str,version:int)->LLMHumanReviewState|None:...
    def by_invocation(self,invocation_id:str)->tuple[LLMHumanReviewEvent,...]:...
    def by_correlation(self,correlation_id:str)->tuple[LLMHumanReviewEvent,...]:...
class LLMHumanReviewRepository(LLMHumanReviewQueryPort,Protocol):
    def append(self,event:LLMHumanReviewEvent)->None:...
class HumanReviewExactQueryPort(Protocol):
    def get_exact(self,reference:PersistedHumanReviewReference)->LLMHumanReviewEvent:...
class HumanReviewExactReferenceRepository(HumanReviewExactQueryPort,Protocol):
    def reference_for(self,event:LLMHumanReviewEvent,draft_reference)->PersistedHumanReviewReference:...
class UpstreamReviewGovernancePort(Protocol):
    def constraints(self,reference)->UpstreamReviewConstraints:...
class LLMHumanReviewAuditPort(Protocol):
    def append(self,event:LLMHumanReviewSecurityEvent)->None:...
    def history(self,correlation_id:str)->tuple[LLMHumanReviewSecurityEvent,...]:...
