from __future__ import annotations
from datetime import datetime
from typing import Protocol
from jmoraIs.patient_context.domain import PatientContext
from .domain import PatientClinicalState,ClinicalStateAuditEvent
from .exact_reference import PersistedClinicalStateReference,PersistedClinicalStateTimelineReference

class PatientContextQueryPort(Protocol):
    def current(self,patient_id:str)->PatientContext: ...
    def at(self,patient_id:str,as_of:datetime)->PatientContext: ...
    def history(self,patient_id:str)->tuple[PatientContext,...]: ...
class ClinicalStateRepository(Protocol):
    def append(self,state:PatientClinicalState)->None: ...
    def get(self,state_id:str)->PatientClinicalState|None: ...
    def latest(self,patient_id:str)->PatientClinicalState|None: ...
    def at(self,patient_id:str,as_of:datetime)->PatientClinicalState|None: ...
    def history(self,patient_id:str)->tuple[PatientClinicalState,...]: ...
class ClinicalStateExactReferenceQueryPort(Protocol):
    def get_exact(self,reference:PersistedClinicalStateReference)->PatientClinicalState: ...
    def get_timeline_exact(self,reference:PersistedClinicalStateTimelineReference)->tuple[PatientClinicalState,...]: ...
class ClinicalStateExactReferenceRepository(ClinicalStateExactReferenceQueryPort,Protocol):
    def reference_for(self,state:PatientClinicalState)->PersistedClinicalStateReference: ...
    def timeline_reference_for(self,references:tuple[PersistedClinicalStateReference,...])->PersistedClinicalStateTimelineReference: ...
class ClinicalStateAuditPort(Protocol):
    def append(self,event:ClinicalStateAuditEvent)->None: ...
    def history(self,patient_id:str)->tuple[ClinicalStateAuditEvent,...]: ...
class ClinicalNormalizerPort(Protocol):
    def normalize(self,category:str,value:str)->str|None: ...
