from __future__ import annotations

from typing import Protocol

from .domain import AuthenticatedPrincipal, ExternalIdentityLink, IdentitySecurityEvent


class IdentityProviderPort(Protocol):
    homologation_safe: bool
    def validate(self, token: str, correlation_id: str) -> AuthenticatedPrincipal: ...
    def readiness(self): ...


class SigningKeyProviderPort(Protocol):
    def resolve(self, key_id: str, algorithm: str): ...
    def refresh(self) -> None: ...
    def readiness(self): ...


class ExternalIdentityLinkRepository(Protocol):
    def create(self, link: ExternalIdentityLink) -> None: ...
    def get(self, provider: str, external_subject: str) -> ExternalIdentityLink | None: ...
    def set_status(self, provider: str, external_subject: str, status, occurred_at) -> ExternalIdentityLink: ...
    def readiness(self): ...


class IdentitySecurityAuditPort(Protocol):
    def append(self, event: IdentitySecurityEvent) -> None: ...
    def history(self, correlation_id: str) -> tuple[IdentitySecurityEvent, ...]: ...
