from __future__ import annotations
from typing import Protocol
from .session_domain import AuthenticatedSession, SessionRevocationEvent, SessionStatus, SessionValidationRequest

class SessionRepository(Protocol):
    def recognize(self, session: AuthenticatedSession) -> AuthenticatedSession: ...
    def get(self, session_id: str) -> AuthenticatedSession | None: ...
    def status(self, session_id: str, principal_id: str) -> SessionStatus: ...
    def append_event(self, event: SessionRevocationEvent) -> None: ...
    def readiness(self): ...

class ReplayProtectionRepository(Protocol):
    def consume(self, *, jti_hash: str, session: AuthenticatedSession, consumed_at, single_use: bool) -> bool: ...
    def readiness(self): ...

class SessionValidationPort(Protocol):
    def validate(self, request: SessionValidationRequest) -> None: ...
    def readiness(self): ...

class SessionRevocationPort(Protocol):
    def revoke_session(self, session_id: str, principal_id: str, tenant_id: str, *, reason: str, correlation_id: str): ...
    def revoke_principal(self, principal_id: str, tenant_id: str, *, reason: str, correlation_id: str): ...
    def suspend_session(self, session_id: str, principal_id: str, tenant_id: str, *, reason: str, correlation_id: str): ...
