from __future__ import annotations
from typing import Protocol
from .domain import PatientContext
from .exact_reference import PersistedPatientContextReference

class PatientContextRepository(Protocol):
    def append(self, context: PatientContext) -> None: ...
    def get(self, context_id: str) -> PatientContext | None: ...
    def latest(self, patient_id: str) -> PatientContext | None: ...
    def history(self, patient_id: str) -> tuple[PatientContext,...]: ...

class PatientContextExactReferencePort(Protocol):
    def reference_for(self, context: PatientContext) -> PersistedPatientContextReference: ...
    def get_exact(self, reference: PersistedPatientContextReference) -> PatientContext: ...
