from __future__ import annotations
from typing import Protocol
from .domain import PatientContext
from .privacy import *

class ClinicalDataAuthorizationPort(Protocol):
    def authorize(self, request: AuthorizationRequest, legal_basis: LegalBasis) -> AuthorizationDecision: ...
class PatientIdentityMappingPort(Protocol):
    def resolve(self, identity_reference: str, authorization: AuthorizationDecision) -> IdentityMapping | None: ...
    def store(self, mapping: IdentityMapping) -> None: ...
class PseudonymizationPort(Protocol):
    def pseudonymize(self, identity_reference: str) -> str: ...
class DeidentificationPort(Protocol):
    def transform(self, fields: tuple[ClassifiedClinicalField,...], pseudonymous_patient_id: str) -> DeidentificationResult: ...
class DataMinimizationPort(Protocol):
    def minimize(self, fields: tuple[ClassifiedClinicalField,...], purpose: PurposeOfUse) -> tuple[ClassifiedClinicalField,...]: ...
class ClinicalAccessAuditRepository(Protocol):
    def append(self, event: ClinicalAccessAuditEvent) -> None: ...
    def history(self, pseudonymous_patient_id: str | None = None) -> tuple[ClinicalAccessAuditEvent,...]: ...

class AuthorizedClinicalIngestionQueryPort(Protocol):
    def get(self, ingestion_record_id: str) -> AuthorizedClinicalIngestionRecord | None: ...
    def get_by_context(self, context_id: str, version: int) -> AuthorizedClinicalIngestionRecord | None: ...
    def by_correlation(self, correlation_id: str) -> tuple[AuthorizedClinicalIngestionRecord, ...]: ...

class AuthorizedClinicalIngestionRepository(AuthorizedClinicalIngestionQueryPort, Protocol):
    def append_atomic(self, context: PatientContext, record: AuthorizedClinicalIngestionRecord,
                      audit_events: tuple[ClinicalAccessAuditEvent, ...]) -> None: ...
