#!/usr/bin/env python3
"""Build the scientific justification draft (Markdown) from confirmed physician decisions.

Input is the JSON written by `scripts/classify_evidence.py --out`. Every item is
re-verified (abstract hash, verbatim quote, PubMed/Crossref VERIFIED status,
strict Vancouver) before it is included; nothing is generated by a model. The
output is a draft that the responsible physician must review and sign.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import sys

from jmoraIs.application.evidence_packages import ScientificEvidencePackagePort
from jmoraIs.application.scientific_justification import JustificationRejected, build_justification, render_markdown
from jmoraIs.application.scientific_verification import AuthoritativeReconciliationPipeline
from jmoraIs.connect.crossref import CrossrefConnector
from jmoraIs.connect.pubmed import PubMedConnector
from jmoraIs.infrastructure import InMemoryPackageCatalogRepository


def main(argv=None, *, pubmed=None, crossref=None, write=print) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--decisions", required=True, help="JSON from classify_evidence.py --out")
    parser.add_argument("--claim", help="Claim to justify (default: the claim in the decisions file)")
    parser.add_argument("--out", required=True, help="Markdown file to write")
    args = parser.parse_args(argv)
    try:
        records = json.loads(Path(args.decisions).read_text())
        if not isinstance(records, list) or not all(isinstance(r, dict) for r in records):
            raise ValueError("decisions file must be a JSON list of objects")
    except (OSError, ValueError) as exc:
        parser.error(f"cannot read decisions: {exc}")
    claims = {" ".join(str(r.get("claim") or "").split()) for r in records}
    claim = args.claim or (claims.pop() if len(claims) == 1 else None)
    if not claim:
        parser.error("decisions cover several claims; pass --claim")
    pubmed = pubmed or PubMedConnector()
    packages = ScientificEvidencePackagePort(catalog=InMemoryPackageCatalogRepository())
    pipeline = AuthoritativeReconciliationPipeline(pubmed=pubmed, crossref=crossref or CrossrefConnector(), packages=packages)
    try:
        draft = build_justification(claim, records, pubmed=pubmed, pipeline=pipeline, packages=packages,
                                    clock=lambda: datetime.now(timezone.utc))
    except JustificationRejected as exc:
        parser.error(str(exc))
    out = Path(args.out)
    out.write_text(render_markdown(draft))
    out.chmod(0o600)
    write(f"{len(draft.references)} reference(s) included, {len(draft.excluded)} excluded -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
