from __future__ import annotations
from typing import Protocol
from .domain import *
class GuidelineQueryPort(Protocol):
    def applicable(self,guideline_ids:tuple[str,...])->tuple[GovernedGuidelineRecommendation,...]:...
class GuidelineRepository(Protocol):
    def append(self,value:GovernedGuidelineRecord)->None:...
    def get(self,record_id:str)->GovernedGuidelineRecord|None:...
    def current(self,guideline_id:str)->GovernedGuidelineRecord|None:...
    def history(self,guideline_id:str)->tuple[GovernedGuidelineRecord,...]:...
class RecommendationRepository(Protocol):
    def append(self,value:GuidelineRecommendationSet)->None:...
    def latest(self,subject_reference:str)->GuidelineRecommendationSet|None:...
    def history(self,subject_reference:str)->tuple[GuidelineRecommendationSet,...]:...
class GuidelineRecommendationQueryPort(Protocol):
    def reference_for(self,value:GuidelineRecommendationSet)->PersistedGuidelineRecommendationSetReference:...
    def get_exact(self,reference:PersistedGuidelineRecommendationSetReference)->GuidelineRecommendationSet:...
class RecommendationAuditPort(Protocol):
    def append(self,event:RecommendationAuditEvent)->None:...
    def history(self,subject_reference:str)->tuple[RecommendationAuditEvent,...]:...
class GovernedEvidenceLifecyclePort(Protocol):
    def current_status(self,evidence)->str:...
class GovernedTerminologyConceptQueryPort(Protocol):
    def get(self,concept_id:str):...
