from __future__ import annotations
from typing import Protocol
from .domain import *
from .exact_reference import PersistedLLMInvocationReference
class LLMGateway(Protocol):
    def invoke(self,request:LLMRequest)->LLMResponse:...
class PromptRepository(Protocol):
    def append(self,value:PromptVersion)->None:...
    def get(self,prompt_version_id:str)->PromptVersion|None:...
    def history(self,template_id:str)->tuple[PromptVersion,...]:...
class PromptAuditRepository(Protocol):
    def append(self,event:PromptAudit)->None:...
    def history(self,request_id:str)->tuple[PromptAudit,...]:...
    def history_by_correlation(self,correlation_id:str)->tuple[PromptAudit,...]:...
class InvocationRepository(Protocol):
    def append(self,value:LLMInvocation)->None:...
    def history(self,request_id:str)->tuple[LLMInvocation,...]:...
    def history_by_correlation(self,correlation_id:str)->tuple[LLMInvocation,...]:...
class LLMInvocationQueryPort(Protocol):
    def get_exact(self,reference:PersistedLLMInvocationReference)->LLMInvocation:...
class LLMInvocationExactReferenceQueryPort(LLMInvocationQueryPort,Protocol):
    pass
class LLMInvocationExactReferenceRepository(LLMInvocationQueryPort,Protocol):
    def reference_for(self,invocation:LLMInvocation)->PersistedLLMInvocationReference:...
class LLMInvocationContextQueryPort(Protocol):
    def get(self,request_id:str)->LLMInvocationContext|None:...
    def history_by_correlation(self,correlation_id:str)->tuple[LLMInvocationContext,...]:...
    def status(self,request_id:str)->InvocationContextPersistenceStatus:...
class LLMInvocationContextRepository(LLMInvocationContextQueryPort,Protocol):
    def append(self,value:LLMInvocationContext)->None:...
class ProviderAdapter(Protocol):
    provider:LLMProvider
    def invoke(self,request:ProviderRequest)->ProviderResponse:...
