from __future__ import annotations
from typing import Protocol,Union
from .domain import *
TerminologyRecord=Union[ClinicalConcept,ConceptMapping,TerminologyVersion,ConceptRelationship]
class TerminologyRepository(Protocol):
    def append(self,stream_id:str,record:TerminologyRecord)->None:...
    def latest(self,stream_id:str)->TerminologyRecord|None:...
    def history(self,stream_id:str)->tuple[TerminologyRecord,...]:...
    def search(self,term:str,code_system:CodeSystem,version:str)->tuple[ClinicalConcept,...]:...
    def mappings(self,source_codes:tuple[TerminologyCode,...],target_system:CodeSystem)->tuple[ConceptMapping,...]:...
    def version(self,code_system:CodeSystem,version:str)->TerminologyVersion|None:...
class TerminologyQueryPort(Protocol):
    def resolve(self,term:str,code_system:CodeSystem,version:str)->MappedClinicalConcept:...
    def version_lookup(self,code_system:CodeSystem,version:str)->TerminologyVersion:...
class ConceptMappingPort(Protocol):
    def map_codes(self,source_codes:tuple[TerminologyCode,...],target_system:CodeSystem)->tuple[ConceptMapping,...]:...
class TerminologyAuditPort(Protocol):
    def append(self,event:TerminologyAuditEvent)->None:...
    def history(self,subject_reference:str)->tuple[TerminologyAuditEvent,...]:...
class UnitNormalizationPort(Protocol):
    def normalize(self,value,unit:str,target_unit:str,version:str)->UnitNormalization:...
class TerminologyMappingGovernanceRepository(Protocol):
    def append(self,record:TerminologyMappingGovernanceRecord)->None:...
    def get(self,governance_record_id:str)->TerminologyMappingGovernanceRecord|None:...
    def current_by_concept(self,concept_id:str)->TerminologyMappingGovernanceRecord|None:...
    def history_by_concept(self,concept_id:str)->tuple[TerminologyMappingGovernanceRecord,...]:...
    def by_source_reference(self,source_reference:str)->tuple[TerminologyMappingGovernanceRecord,...]:...
class TerminologyMappingGovernanceQueryPort(Protocol):
    def get(self,governance_record_id:str)->TerminologyMappingGovernanceRecord|None:...
    def current_by_concept(self,concept_id:str)->TerminologyMappingGovernanceRecord|None:...
    def history_by_concept(self,concept_id:str)->tuple[TerminologyMappingGovernanceRecord,...]:...
    def by_source_reference(self,source_reference:str)->tuple[TerminologyMappingGovernanceRecord,...]:...
    def reference_for(self,record:TerminologyMappingGovernanceRecord)->PersistedTerminologyMappingGovernanceReference:...
    def get_exact(self,reference:PersistedTerminologyMappingGovernanceReference)->TerminologyMappingGovernanceRecord:...
