from __future__ import annotations
from typing import Protocol
from .domain import *
class GovernedOrthopedicStateQueryPort(Protocol):
    def get(self,state_reference_id:str)->GovernedOrthopedicStateView:...
class GovernedEvidenceQueryPort(Protocol):
    def get(self,evidence_id:str):...
class GovernedEvidenceLifecyclePort(Protocol):
    def current_status(self,evidence)->str:...
class GuidelineRecommendationQueryPort(Protocol):
    def latest(self,subject_reference:str):...
class GovernedTerminologyQueryPort(Protocol):
    def get(self,concept_id:str):...
class OrthopedicAssessmentRepository(Protocol):
    def append(self,value:OrthopedicAssessmentSet)->None:...
    def latest(self,subject_reference:str)->OrthopedicAssessmentSet|None:...
    def history(self,subject_reference:str)->tuple[OrthopedicAssessmentSet,...]:...
    def reference_for(self,value:OrthopedicAssessmentSet)->PersistedOrthopedicAssessmentSetReference:...
    def get_exact(self,reference:PersistedOrthopedicAssessmentSetReference)->OrthopedicAssessmentSet:...
class OrthopedicAuditPort(Protocol):
    def append(self,event:OrthopedicAuditEvent)->None:...
    def history(self,subject_reference:str)->tuple[OrthopedicAuditEvent,...]:...
